name: AppMap Analysis

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: maven 

      - name: Maven Test
        run: ./mvnw test

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ steps.install-appmap.outputs.appmap-dir }}
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
  
  appmap-analysis:
    if: always()
    needs: [test]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write